version: '3.1'
services:
  app:
    container_name: TransactionTracker
    image: transaction-tracker
    build:
      context: TransactionTrackerSpringBoot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb

  postgresqldb:
    container_name: TransactionTracker_DB
    image: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=transaction
    volumes:
      - db_volume:/var/lib/postgresql/data

  transaction-tracker-angular:
    container_name: transaction-tracker-angular
    build:
        context: TransactionTrackerAngular
        dockerfile: Dockerfile
    ports:
      - "4201:80"


volumes:
  db_volume: { }





